[tool.pytest.ini_options]
pythonpath = [
    ".", "src"
]
env_files = "./secrets/.test.env"
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

filterwarnings="ignore::DeprecationWarning"
